/*
 ===================================================================================================
 Module      : ULTRASONIC
 File Name   : ultrasonic.c
 Author      : Mohamed Samy
 Description : Source file for the ULTRASONIC driver
 ===================================================================================================
 */

#include "icu.h"
#include "gpio.h"
#include <util/delay.h>
#include "ultrasonic.h"
#include "common_macros.h"
#include <avr/io.h>
#include <avr/interrupt.h>


/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

static uint16 g_echo_time = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/


/*
 * Description: Function responsible for initialization of ultrasonic
 * 1. Initialize ICU
 * 2. Setup the ICU callback function
 * 3. Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void)
{

	/* Initialize the ICU */
	ICU_ConfigType config={F_CPU_8,RAISING};
	ICU_init(&config);

	/* Set callback function so (ICU driver) lower layer can call it */
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	/*
	 * Setup direction of trigger pin as OUTPUT
	 * Initialize the pin by setting it to LOW
	 */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, PIN_OUTPUT);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}

/*
 * Description: Function responsible for sending the trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger(void)
{

	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_HIGH);

	_delay_ms(10);

	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}

/*
 * Function Description: Function responsible for reading distance using ultrasonic sensor.
 *  1. Send the trigger pulse by using Ultrasonic_Trigger function so the ultrasonic sensor starts to produce echo pulse
 *  2. Start the measurements by the Input Capture Unit (ICU) from this moment
 *
 *	Return: The measured distance in centimeters
 */
uint16 Ultrasonic_readDistance(void)
{

	Ultrasonic_Trigger();

	return ((g_echo_time * 0.017)+2);
}

/*
 * Function Description:
 * This is the callback function called by the ICU driver.
 * We initialize the callback in Ultrasonic_init().
 * The function is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void){
	static uint8 g_edgeCount = 0;

	g_edgeCount++;

	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */

		ICU_clearTimerValue();

		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{

		/* Store the High time value */
		g_echo_time = ICU_getInputCaptureValue();
		/* Detect rising edge */
		ICU_setEdgeDetectionType(RAISING);


		g_edgeCount = 0;
	}
}






